INSERT INTO access_management_engine_user (
    id,
    username,
    email_address,
    password,
    role,
    created_on,
    last_update_on
)
VALUES
(
    1,
    'admin',
    'admin@sitekit.com',
    '$2a$12$1i/JVR8ohnDMYMPTWYKHB.TFND79ZhDOjKzkAilsHmjC6I.Gup01m',
    'ADMIN',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    2,
    'user1',
    'user1@sitekit.com',
    '$2a$12$ORh6nwiJhF52jadkoFbQ7OtJWxkXek1qXJpN0RKoD5Nq2UYETz91W',
    'USER',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
